version: "3"

volumes:
  mariadb_keycloak_data:
    driver: local

services:
  mariadb-keycloak:
    image: mariadb
    volumes:
      - mariadb_keycloak_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
  keycloak:
    image: quay.io/keycloak/keycloak:11.0.3
    environment:
      DB_VENDOR: mariadb
      DB_ADDR: mariadb-keycloak
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    command: ["-b 0.0.0.0"]
    ports:
      - 8180:8080
    depends_on:
      - mariadb-keycloak
